"""empty message

Revision ID: 590fb12db843
Revises: 762d154fb6f6
Create Date: 2022-06-06 23:41:44.692166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590fb12db843'
down_revision = '762d154fb6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('quest_pos', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'quest_pos')
    # ### end Alembic commands ###
