"""empty message

Revision ID: 762d154fb6f6
Revises: 4570fac0a068
Create Date: 2022-06-06 21:58:50.102444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762d154fb6f6'
down_revision = '4570fac0a068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_quest_complete', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('second_quest_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'second_quest_complete')
    op.drop_column('user', 'first_quest_complete')
    # ### end Alembic commands ###
